### PR TITLE
refactored file upload feature and added tests (closes #45)

### LINKED ISSUE #45: Capacité à uploader un fichier pour les configurations
## Idées

L'upload de fichier vers le serveur semble complètement inutile et pourrait provoquer une surchage à gérer. Par contre, on peut utiliser jQuery/Javascript pour lire le contenu d'un fichier et remplir les textarea :)

## Ressources : 

- https://www.html5rocks.com/en/tutorials/file/dndfiles/
- https://stackoverflow.com/questions/12281775/get-data-from-file-input-in-jquery

### First situation

1. As a normal user, when I create a corpus
2. Click New Corpus
3. Click on <kbd>Write your own</kbd> to show the control list creation as well
3. Fields `#tokens` and `#allowed_lemma`, `#allowed_POS` and `#allowed_morph` need to received huge amount of data, most of the time they are copy pasted

### Second situation

1. As a control list administrator, when I want to edit a control list, 
2. Click on <kbd>Control List</kbd> > Any control list you contorl.
3. On the home page of the control list, 3 yellow buttons are visible, they all start with rewrite
4. On their page, a single field need to received huge amount of data, most of the time they are copy pasted

image

## Expected Behaviour

Add a button so that

1. User can click upload file
2. The file is read client side and inserted in the text area.

### PR DESCRIPTION
**Pull request by carinedengler**
* refactored file upload feature and re-use it for edting control lists
* added test cases for corpus creation and editing of control lists

### CODE REVIEW

**Comment by carinedengler** [comment]
there are 3 tests in tests/test_selenium/test_token_correct.py which do not pass ; they are not passing on the head of your branch as well

**Comment by PonteIneptique** [comment]
LGTM

**Comment by PonteIneptique** [comment]
> there are 3 tests in tests/test_selenium/test_token_correct.py which do not pass ; they are not passing on the head of your branch as well

Yes, we unfortunately know. Those three tests have been bugging me for months... :'(

**Review by MrGecko — APPROVED** [review]
nice implementation, thank you

**Pull request merged**
