### PR TITLE
Integrated flake8 to travis CI

### PR DESCRIPTION
**Pull request by AdityaJ7**
Integrated flake8 to the travis CI.

This PR is connected to issue #210

### CODE REVIEW

**Comment by PonteIneptique** [comment]
I am sorry it took me so long to get back to you...

Could you limit to 120 chars, as said in the issue ?

**Comment by AdityaJ7** [comment]
> I am sorry it took me so long to get back to you...
> 
> Could you limit to 120 chars, as said in the issue ?

Sure

**Comment by PonteIneptique** [comment]
I assume you came for Hacktoberfest ? I made sure the issue was tagged appropriately ;)

**Comment by AdityaJ7** [comment]
> I assume you came for Hacktoberfest ? I made sure the issue was tagged appropriately ;)

Nah, it's fine I am done with Hacktoberfest.

**Comment by PonteIneptique** [comment]
Well thanks :1st_place_medal:

**Comment by AdityaJ7** [comment]
> Well thanks 🥇

Happy to help @PonteIneptique

**Pull request merged**
