### PR TITLE
Full i18n / l10n rework

### PR DESCRIPTION
**Pull request by PonteIneptique**
Adapted from #284 to add support for user customization and some cleaning.

@Lungsang-bod can you check this ?

### CODE REVIEW

**Comment by Lungsang-bod** [comment]
> Adapted from #284 to add support for user customization and some cleaning.
> 
> @Lungsang-bod can you check this ?

Hello @PonteIneptique , so sorry i was caught up with my new project and didn't get to see activities here on pyrrha localization PR. I will check and let you know ASAP :)

**Comment by Lungsang-bod** [comment]
file:///home/lungsang/Videos/Screencasts/Screencast%20from%2008-08-22%2012:34:53%20PM%20IST.webm
Hello @PonteIneptique, language is not changing in my browser. I have shared a video demo of my browser. Can you please check what might be the cause.

**Comment by Lungsang-bod** [comment]
Snapshot of #285 in browser

**Comment by Lungsang-bod** [comment]
Hello @PonteIneptique , I tried in different ways but language is not changing in my browser. Can you please check what might be the cause. Below is a clipshot link of what i tried to did :) 
https://drive.google.com/file/d/11uQtyNjMdOuBizDWwvaXEnsWPxBOfKPZ/view?usp=sharing

**Comment by PonteIneptique** [comment]
Hi :)
I'm literally on vacation, 600km from my home and without laptop, so I
might not be able to tell much.
Just to make sure, did you run

python manage.py translate update
# Change the translation and then do
python manage.py translate compile

python manage.py db-upgrade user-languag


Le lun. 8 août 2022 à 9:28 AM, Lungsang-bod ***@***.***> a
écrit :

**Comment by Lungsang-bod** [comment]
It is working now, looks like i missed ```python manage.py translate compile```
Thank you! Have a great day ahead :)

**Comment by PonteIneptique** [comment]
If this work, I'll merge then 😊

Le lun. 8 août 2022 à 10:12 AM, Lungsang-bod ***@***.***> a
écrit :

**Comment by Lungsang-bod** [comment]
Great! Thank you :) regarding the non-translated strings, i will PR them as soon as possible when they are done:)

**Pull request merged**
