### PR TITLE
Localization : Tibetan

### PR DESCRIPTION
**Pull request by lungsang**

### CODE REVIEW

**Comment by PonteIneptique** [comment]
Hey @lungsang !
This looks promising. I just saw your message in #198 
Can you try this way:

```py
import os
from flask import Flask, g

from config import config
from flask_compress import Compress
from flask_login import LoginManager
from flask_mail import Mail
from flask_sqlalchemy import SQLAlchemy
from flask_wtf import CSRFProtect
from flaskext.markdown import Markdown
from flask_babel import Babel 

basedir = os.path.abspath(os.path.dirname(__file__)) 

mail = Mail()
db = SQLAlchemy()
csrf = CSRFProtect()
babel = Babel()
compress = Compress()
# Set up Flask-Login
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'account.login'

app = Flask(
        __name__,
        template_folder=config["dev"].template_folder,
        static_folder=config["dev"].static_folder,
        static_url_path="/statics"
    )


@babel.localeselector
def get_locale():
    return 'bo_CN'

def create_app(config_name="dev"):
    """ Create the application """
    if not isinstance(config_name, str):
        app.config.from_object(config)
    else:
        app.config.from_object(config[config_name])

    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    config[config_name].init_app(app)

    # Set up extensions
    mail.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    #csrf.init_app(app)
    compress.init_app(app)
    babel.init_app(app)
    md = Markdown(app, safe_mode=True)
    #assets_env = Environment(app)

    # Register Jinja template functions
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .account import account as account_blueprint
    app.register_blueprint(account_blueprint, url_prefix='/account')

    from .admin import admin as admin_blueprint
    app.register_blueprint(admin_blueprint, url_prefix='/admin')

    from .configurations import configuration as configurations_blueprint
    app.register_blueprint(configurations_blueprint)

    from .control_lists import control_lists_bp
    app.register_blueprint(control_lists_bp)

    return app
```

**Comment by Lungsang-bod** [comment]
Hello @PonteIneptique, thank you for your quick response! 
Yes, I tried the above code and, the browser is still not picking up the required langauge.

Another way I tried is, I inherit the create_app function in babel , I dont know if its the right way
```
import os
from flask import Flask, g

from config import config
from flask_compress import Compress
from flask_login import LoginManager
from flask_mail import Mail
from flask_sqlalchemy import SQLAlchemy
from flask_wtf import CSRFProtect
from flaskext.markdown import Markdown
from flask_babel import Babel 

basedir = os.path.abspath(os.path.dirname(__file__)) 

mail = Mail()
db = SQLAlchemy()
csrf = CSRFProtect()
compress = Compress()
# Set up Flask-Login
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'account.login'


def create_app(config_name="dev"):
    """ Create the application """

    app = Flask(
        __name__,
        template_folder=config[config_name].template_folder,
        static_folder=config[config_name].static_folder,
        static_url_path="/statics"
    )

    if not isinstance(config_name, str):
        app.config.from_object(config)
    else:
        app.config.from_object(config[config_name])

    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    config[config_name].init_app(app)

    # Set up extensions
    mail.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    #csrf.init_app(app)
    compress.init_app(app)
    babel.init_app(app)
    md = Markdown(app, safe_mode=True)
    #assets_env = Environment(app)

    # Register Jinja template functions
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .account import account as account_blueprint
    app.register_blueprint(account_blueprint, url_prefix='/account')

    from .admin import admin as admin_blueprint
    app.register_blueprint(admin_blueprint, url_prefix='/admin')

    from .configurations import configuration as configurations_blueprint
    app.register_blueprint(configurations_blueprint)

    from .control_lists import control_lists_bp
    app.register_blueprint(control_lists_bp)

    return app

babel = Babel(create_app)
@babel.localeselector
def get_locale():
    return 'bo_CN'
```
 Then I am getting this error:

```
Traceback (most recent call last):
  File "/mnt/c/Users/Lungsang/Desktop/Pyrrha-Related/old-pyrrha/manage.py", line 2, in <module>
    from app.cli import make_cli
  File "/mnt/c/Users/Lungsang/Desktop/Pyrrha-Related/old-pyrrha/app/__init__.py", line 72, in <module>
    babel = Babel (create_app)
  File "/mnt/c/Users/Lungsang/Desktop/pyrrha/env/lib/python3.8/site-packages/flask_babel/__init__.py", line 63, in __init__
    self.init_app(app)
  File "/mnt/c/Users/Lungsang/Desktop/pyrrha/env/lib/python3.8/site-packages/flask_babel/__init__.py", line 75, in init_app
    app.config.setdefault('BABEL_DEFAULT_LOCALE', self._default_locale)
AttributeError: 'function' object has no attribute 'config'
```

**Comment by Lungsang-bod** [comment]
In this [youtube tutorial](https://www.youtube.com/watch?v=bcm_zjjJ1Rs&t=1674s) around 1:58 min, the init.py module is shown. He is translating in arab and its working fine at the end. I tried it in pyrrha, and its not working.

**Comment by PonteIneptique** [comment]
Hi :)
I am on sick leave until Thursday, but I'll have a look as soon as possible :)

**Comment by Lungsang-bod** [comment]
Sure, thank you. Hope you get well soon.

**Comment by Lungsang-bod** [comment]
> Hello @PonteIneptique, In this [youtube tutorial](https://www.youtube.com/watch?v=bcm_zjjJ1Rs&t=1674s) around 6:59 min, the init.py module is shown. He is translating in arab and its working fine.

Hi @PonteIneptique, can you please have a look when time permit you :)

**Comment by PonteIneptique** [comment]
Oh, I completely forgot to take a look at it after my sick leave. I'll have a go at it today or tomorrow !

**Comment by Lungsang-bod** [comment]
thank you !

**Comment by PonteIneptique** [comment]
https://github.com/hipster-philology/pyrrha/pull/276/commits/334ae3a69fe66eed6ae1db4ba5f5f40600d50350 should allow you to run your Babel. You should pull / fetch your branch

1. Don't forget to run the app from the root of the "pyrrha" folder, with the command `python manage.py run`
2. Don't forget to compile your translations with `pybabel compile -d translations`
3. Enjoy ;)

**Comment by lungsang** [comment]
Thank you @PonteIneptique, It's working fine now ! 
Have a great day ahead :)

**Comment by PonteIneptique** [comment]
Hey :) Feel free to tell me when this is ready to be merged :)

**Comment by Lungsang-bod** [comment]
Okay :)

**Comment by PonteIneptique** [comment]
Hi @Lungsang-bod , you should probably have a look at #281 that will probably help run tests...

**Comment by PonteIneptique** [comment]
Hey :)
There is one incoming change that might brake your current translation, I just wanted to make sure you saw the incoming PR (and so that you can give some feedback too)
image
See #282

**Comment by Lungsang-bod** [comment]
Okay @PonteIneptique, i will check the new changes and will get back to you :) Thank you for letting me know!

**Comment by Lungsang-bod** [comment]
Hi @PonteIneptique :) The new menu design looks much better than the previous one in my opinion :) 
Should our translation PR wait till  #282 is merged ?

**Comment by PonteIneptique** [comment]
> Hi @PonteIneptique :) The new menu design looks much better than the previous one in my opinion :) Please let me know when #282 is merged ! Other than the new menu , our translation is ready to be merged ;)

I am gonna merge the PR today :)

**Comment by PonteIneptique** [comment]
You should be able to rebase / merge and fix the various conflicts :)

**Comment by Lungsang-bod** [comment]
> You should be able to rebase / merge and fix the various conflicts :)

Okay :)

**Comment by Lungsang-bod** [comment]
Hi @PonteIneptique :) I have send PR of localized pyrrha here : #284  
I tried to make the changes as clean as it get, please have a look and hope you will merge it soon ;)

**Comment by PonteIneptique** [comment]
I am closing this one and I will check what's going on with your proposal later this week or next week (hopefuly)

**Comment by PonteIneptique** [comment]
Thanks for your work !

**Comment by Lungsang-bod** [comment]
> I am closing this one and I will check what's going on with your proposal later this week or next week (hopefuly)

Thank you :) @PonteIneptique

**Pull request closed without merging**
