### PR TITLE
tibetan-translation

### PR DESCRIPTION
**Pull request by Lungsang-bod**
Hello @PonteIneptique, Here are the remaining translated strings of Tibetan. Can you please merge it when you have time. 
Thank you in advance :)

### CODE REVIEW

**Comment by PonteIneptique** [comment]
I'll merge as soon as the tests pass.
In the meanwhile, have you ahad time to find out if people published paper or slides about your work or work using pyrrha?

**Review by PonteIneptique — APPROVED** [review]

**Comment by Lungsang-bod** [comment]
> I'll merge as soon as the tests pass. In the meanwhile, have you ahad time to find out if people published paper or slides about your work or work using pyrrha?

I have asked them just today again, will let you know if there are any when I get the reply :)

**Comment by PonteIneptique** [comment]
Great :) 
In addition, could you provide me your information so that I add you to our CITATION.CFF file ?

```yml
  - family-names: Clérice
    given-names: Thibault
    orcid: https://orcid.org/0000-0003-1852-9204
```

(ORCID is optional)

**Comment by Lungsang-bod** [comment]
Hello @PonteIneptique I didn't get reply yet about the paper or slide yet. I will pass to you when they let me know :) 
For CITATION.CFF file
``` give-name:  Lungsang ```

Thank you :)

**Pull request merged**
